- name: demonstrate loop
  hosts: localhost
  gather_facts: no

  vars:
    list_one:
      - cyan
      - magenta
      - yellow
      - key

  tasks:
    - name: with_list
      ansible.builtin.debug:
        msg: "{{ item }}"
      with_list: '{{ list_one }}'

    - name: with_list -> loop
      ansible.builtin.debug:
        msg: "{{ item }}"
      loop: '{{ list_one }}'