- name: demonstrate loop with flatten
  hosts: localhost
  gather_facts: false

  vars:
    list_one:
      - /usr
        - /share
          - /themes
          - /vim
          - /zsh
        - /lib
        - /bin
      - /var
        - /log
      - /home

  tasks:
    - name: with_flattened
      ansible.builtin.debug:
        msg: "{{ item }}"
      with_flattened: "{{ list_one }}"

    - name: with_flattened -> loop
      ansible.builtin.debug:
        msg: "{{ item }}"
      loop: "{{ list_one|flatten }}"
