- name: demonstrate loop with flatten
  hosts: localhost
  gather_facts: no

  vars:
    list_one:
      - reds
        - carnation
        - violet
        - scarlet
      - greens
        - seafoam
        - inchworm
        - jade
      - blues
        - azure
        - cyan
        - denim

  tasks:
    - name: with_items
      ansible.builtin.debug:
        msg: "{{ item }}"
      with_items: "{{ list_one }}"

    - name: with_items -> loop
      ansible.builtin.debug:
        msg: "{{ item }}"
      loop: "{{ list_one|flatten(levels=1) }}"