- name: demonstrate loop with product
  hosts: localhost
  gather_facts: false

  vars:
    list_one:
      - cyan
      - magenta
      - yellow
      - key
    list_two:
      - light
      - medium
      - dark

  tasks:
    - name: with_nested
      ansible.builtin.debug:
        msg: "{{ item.0 }} - {{ item.1 }}"
      with_nested:
        - "{{ list_one }}"
        - "{{ list_two }}"

    - name: with_nested -> loop
      ansible.builtin.debug:
        msg: "{{ item.0 }} - {{ item.1 }}"
      loop: "{{ list_one|product(list_two)|list }}"
