- name: demonstrate loop
  hosts: localhost
  gather_facts: false

  vars:
    list_one:
      - cyan
      - magenta
      - yellow
      - key

  tasks:
    - name: with_indexed_items
      ansible.builtin.debug:
        msg: "{{ item.0 }} - {{ item.1 }}"
      with_indexed_items: "{{ list_one }}"

    - name: with_indexed_items -> loop
      ansible.builtin.debug:
        msg: "{{ index }} - {{ item }}"
      loop: "{{ list_one|flatten(levels=1) }}"
      loop_control:
        index_var: index
